"use strict";

module.exports = {
  up: (queryInterface, Sequelize) => {
    return queryInterface.bulkInsert(
      "Tasks",
      [
        {
          id: 1,
          customer_first_name: "Faith",
          customer_last_name: "Kanini",
          personnel_first_name: "Muni",
          personnel_other_name: "Kamau",
          agentId: "40546",
          assigned: "yes",
          in_progress: "InProgress",
          completed: "Completed",
          deferred: "Deffered",
          status: "Complete",
          location: "Embu",
          gender: "Female",
          age: "34",
          access_code: "40100",
          splash_page: "",
          mpesa: "0713777624",
          autoplay: "yes",
          comments: "Great Job ",
          registration: "Complete",
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          id: 2,
          customer_first_name: "John",
          customer_last_name: "Otieno",
          personnel_first_name: "Alfred",
          personnel_other_name: "Mutua",
          agentId: "40546",
          assigned: "yes",
          in_progress: "InProgress",
          completed: "Completed",
          deferred: "Deffered",
          status: "Complete",
          location: "Embu",
          gender: "Female",
          age: "34",
          access_code: "40100",
          splash_page: "",
          mpesa: "0713777624",
          autoplay: "yes",
          comments: "Great Job ",
          registration: "Complete",
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          id: 3,
          customer_first_name: "Kevin",
          customer_last_name: "Makau",
          personnel_first_name: "Jesinter",
          personnel_other_name: "Kore",
          agentId: "40546",
          assigned: "yes",
          in_progress: "InProgress",
          completed: "Completed",
          deferred: "Deffered",
          status: "Complete",
          location: "Embu",
          gender: "Female",
          age: "34",
          access_code: "40100",
          splash_page: "",
          mpesa: "0713777624",
          autoplay: "yes",
          comments: "Great Job ",
          registration: "Complete",
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          id: 4,
          customer_first_name: "Benedict",
          customer_last_name: "Asimaje",
          personnel_first_name: "Benard",
          personnel_other_name: "Kariuki",
          agentId: "40546",
          assigned: "yes",
          in_progress: "InProgress",
          completed: "Completed",
          deferred: "Deffered",
          status: "Complete",
          location: "Embu",
          gender: "Female",
          age: "34",
          access_code: "40100",
          splash_page: "",
          mpesa: "0713777624",
          autoplay: "yes",
          comments: "Great Job ",
          registration: "Complete",
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          id: 5,
          customer_first_name: "Ken",
          customer_last_name: "Mwanzi",
          personnel_first_name: "Francis",
          personnel_other_name: "Konyach",
          agentId: "40546",
          assigned: "yes",
          in_progress: "InProgress",
          completed: "Completed",
          deferred: "Deffered",
          status: "Complete",
          location: "Embu",
          gender: "Female",
          age: "34",
          access_code: "40100",
          splash_page: "",
          mpesa: "0713777624",
          autoplay: "yes",
          comments: "Great Job ",
          registration: "Complete",
          createdAt: new Date(),
          updatedAt: new Date()
        }
        
      ],
      {}
    );
  },

  down: (queryInterface, Sequelize) => {
    return queryInterface.bulkDelete("Tasks", null, {});
  }
};
